=== rahulvijayaTG/edm/bcmclient/WEB-INF/system/context/dtd/resolvers.dtd
<!ELEMENT resolvers (resolver+)>

<!ELEMENT resolver (init?, include*)>
<!ATTLIST resolver name ID #REQUIRED>
<!ATTLIST resolver class CDATA #REQUIRED>
<!ATTLIST resolver description CDATA #REQUIRED>

<!ELEMENT include EMPTY>
<!ATTLIST include resolver IDREF #REQUIRED>


<!ELEMENT init (attribute+)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute name CDATA #REQUIRED
                    value CDATA #REQUIRED
>

=== rahulvijayaTG/edm/bcmclient/WEB-INF/system/context/xml/resolvers.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE resolvers SYSTEM "../dtd/resolvers.dtd"> -->

<resolvers>
  <resolver name="pages" class="com.i2.x2.util.web.PageMapResolver" description="Resolve via page map"/>
  <resolver name="xsl" class="com.i2.x2.util.web.XslMapResolver" description="Resolve via xsl map"/>

  <resolver name="application" class="com.i2.x2.context.resolvers.MapResolver"
    description="Resolve via a global static HashMap instance; will serve as application-wide resolver"/>

  <resolver name="I18N" class="com.i2.x2.context.resolvers.ResourceBundleResolver" description="Resource Bundle Support"/>
  <resolver name="session" class="com.i2.x2.context.resolvers.HttpSessionResolver" description="Resolve via session"/>
  <resolver name="request" class="com.i2.x2.context.resolvers.HttpRequestResolver" description="Resolve via request">
    <include resolver="session"/>
  </resolver>

  <resolver 
      name="ConfigContext" 
      class="com.i2.x2.context.resolvers.ConfigContextResolver"
      description="Resolve via current configuration context"
  >
    <init>
      <attribute name="CONFIGALIAS" value="ConfigContext" />
      <attribute name="CONFIGFILE" value="config-context.cfg" />
      <attribute name="CONFIGPATH" value="/WEB-INF/system/context/xml" />
    </init>
  </resolver> 

  <resolver name="default" class="com.i2.x2.context.resolvers.DefaultResolverProxy" description="Resolve via the default resolver">
    <include resolver="request"/>
    <include resolver="session"/>
  </resolver>

  <!--
  <resolver name="Test" class="com.i2.x2.context.resolvers.TestResolver" description="resolver used for testing purposes"/>

  <resolver name="XML" class="com.i2.x2.context.resolvers.XMLResolver" description="very simple XML resolver, no write capabilities">
    <init>
      <attribute name="XML_TO_RESOLVE" value="D:\devel\x2\xapl/conf/context/xml/test.xml" />
    </init>
  </resolver>

  
  <resolver 
      name="File" 
      class="com.i2.x2.context.resolvers.FileResolver" 
      description="very simple File resolver"
  >
    <init>
      <attribute name="FILE_TO_RESOLVE" value="D:\devel\x2\xapl/conf/context/xml/test.txt" />
    </init>

    <include resolver="XML"/>
  </resolver>
    -->

  <resolver name="map" class="com.i2.x2.context.resolvers.MapResolver"
    description="Resolve via a global static HashMap instance; currently used only for testing purposes"/>


</resolvers>
